### ISSUE TITLE
Deduplicate DaService and DaTrait interfaces

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign#170]
Currently, the workflow for processing Da layer block data has two steps. First, data is fetched from the RPC via the `DaService` trait, which is generic over a Future (to enable async) and a `FilteredBlock`, which is corresponds to the Da layer block with the irrelevant data filtered out. In a typical workflow, the returned future is `await`ed immediately and the result is stored in the database. 

Second, the filtered block is retrived from the Database using the `get_relevant_txs_with_proof` from the `DaTrait`, which (in practice) is a relatively thin wrapper around a db lookup. This seems redundant. Since `get_relevant_txs_with_proof` is never called within the state machine (only `verify_relevant_tx_list` is), it seems like all of its work should be pushed into the DaService trait. This would leave us with two traits - DaService, which is responsible for fetching blocks via RPC *and* performing ETL on the returned data, and `DaTrait` which is part of the rollups provable execution and simply retrieves data from the host.

**Comment by preston-evans98** [comment]
@bkolad, curious for your thoughts here

**Comment by bkolad** [comment]
This is a very good idea!
