### ISSUE TITLE
Modules: Bank: Token balances prefix is just address

### ISSUE THREAD

**Issue by citizen-stig** [Sovereign-Labs/sovereign#185]
# Intro

Each module in module system has prefix, based on the cargo crate path and struct name.
For example, bank module has prefix `bank/Bank`
All state attributes of the module struct are sub-prefixes, for example tokens state of the Bank module are prefixed with `bank/Bank/tokens/<TOKEN_ADDRESS>`.

# The problem

Existing macro does not support deeper nesting.
Following bank example, each token map has address of the token and inside it has map of balances for each address.

Currently balance of each user is going to be saved with prefix `<USER_ADDRESS>` . 

This can cause potential conflict between modules if another module has same deeper nesting and uses same prefix, in this case user address.

Imagine 'election' module, where top level state map is `topic => votes` and votes are nested map with `user => candidate`

# More fundamental goal

Developers are need to be aware are need to be aware about prefixes when they store state. 
Can we hide this concept completely? For example each module need to implement some trait like:

```rust

trait Prefixable {
    fn prefix(&self) -> Prefix;
} 
```

So working set will require `Prefixable` trait bound. 

More importantly, do we think it is useful feature?

# Potential solutions

### Developer handle nesting themself.

Pros:
 * Easy to implement, we just allow extending prefixes.
 Cons:
 * Error prone: human is involved
 * Prefix is generated in run-time, which burdens prover.
 
### Macro adds trait bound
 
Each `#[state]` attribute has a trait bound, so if child struct does not have trait bound implemented, it is going to fail compile time

Pros:
* Ensures correctness at compile time
Cons:
* Does not solve problem for deeper nesting, like if grand child has another mapping.
* Still some manual intervention needed.

Maybe we should add trait bound to `StateMap` and `StateVec` so the all have prefix generated at compile time?

### Maco parameters

@preston-evans98 mentioned adding parameters to `#[state(SOMETHING)`

# Note on prefixes readability

Even when prefix problem is solved, prefix can be bytes, which means we cannot represent it in human readable way for nested structures. 

When this issue is resolved, based on the solution we need to come up with idea on how to improve prefixes readability in case of errors.

**Comment by citizen-stig** [comment]
> Token::create takes an additional parent_prefix

This sounds quite reasonable!

**Comment by preston-evans98** [comment]
This seems like a good way to fix the issue for tokens! Is there still a risk of future modules accidentally re-creating the problem with other nested data structure?

**Comment by bkolad** [comment]
> This seems like a good way to fix the issue for tokens! Is there still a risk of future modules accidentally re-creating the problem with other nested data structure?

If we make a pattern out of it, then I think yes.
