### ISSUE TITLE
Migrate from custom Encode/Decode to serde::Serialize/Deserialize

### ISSUE THREAD

**Issue by preston-evans98** [Sovereign-Labs/sovereign#215]
# Background
Currently, we use custom encode/decode traits. The original motivation was to be compatible with non-standard serialization libraries like `borsh` (which we use heavily) and `rykv`. However, over time our traits have evolved to be nearly identical to the serde ones - except that they're not supported in any crates that we don't own. 

## Proposal
We should migrate to `serde`. This can be done in two ways - either write a blanket impl of `Encode/Decode` in terms of `Serialize/Deserialize`, or remove the `Encode/Decode` traits entirely and replace them with Serde. 

To complete the migration, we'll need to get a `serde` compatible version of Borsh. Currently, the `borsh` crate maintains its own macros and traits rather than implementing itself as a serde data format for two reasons - to support the [`borsh init`](https://github.com/near/borsh-rs#features) features (which we don't use), and for a [claimed speed boost](https://github.com/near/borsh). AFAICT, most of the speedup from opting out of serde has to do with skipping deserializating for unsized types - though it may be worth confirming this with benchmarks - and this optimization is known to be unsound.

**Comment by citizen-stig** [comment]
Discussed steps to achieve:

1. Remove our own Encode/Decode trait
2. Derive serde in sdk and do not use borsh there.
3. Use borsh only in modules

**Comment by citizen-stig** [comment]
I consider this one closed in scope of #260 

Couple follow up issues have been created:

1. #262 
2. #263

**Comment by theochap** [comment]
I am undertaking this task now, here are the steps I am performing:
- Designing a serializer for serde compatible with bosh (from serde data model to borsh's)
- Designing a deserializer for serde compatible with bosh (from borsh's data model to serde)
- Adding custom serialization functions for hash_maps in serde

**Comment by citizen-stig** [comment]
Hey @theochap isn't what you are going to do a new issue? 

If yes, please create new issue, so we can track it, as this one was planned to Alpha Milestone.
If no, please just assign it to yourself.

**Comment by citizen-stig** [comment]
Notes from a phone call.

It is unfeasible to have serde compatible borsh serialization, as borsh require deterministic traversal and not all structures guarantee that, such as HashMap. Implementing wrapper structures does not seem like a good solution.

Resolution for this issue is "won't do"
