### ISSUE TITLE
sov-modules: Add `transactions` to the module system.

### ISSUE THREAD

**Issue by bkolad** [Sovereign-Labs/sovereign#73]
If a module method returns early, we need to revert all state-related changes, for example:

```
fn foo(&mut self) -> Result {
   ...
   self.some_value.set(x);
   let v = self.some_other_value.get()?;  <- returns because of an error 
   ...
}
```
Shouldn't persist `x` or any other state change.

**Comment by preston-evans98** [comment]
@bkolad, Should this be part of the Alpha release? Adding for now, feel free to remove.

**Comment by bkolad** [comment]
This is already implemented (we revert in `AppTemplate` in this case), I forgot to close the issue.
