### ISSUE TITLE
sov-modules: Check tx signature outide of the `dispatch_tx` function.

### ISSUE THREAD

**Issue by bkolad** [Sovereign-Labs/sovereign#79]
We need to introduce a `Spec` trait containing information about the cryptographic schema and use it with `Context`.

**Comment by preston-evans98** [comment]
Original context (taken from [here](https://github.com/Sovereign-Labs/sovereign/pull/78#discussion_r1113231684)): 

> It would be great to encode the constraint "Transaction signature must be checked outside of this function" into the type system.
> 
> One potential idea - maybe we should make separate structs for `Context` and `Spec` - the `Spec` struct would contain type information (what signature scheme is being used, etc.), while the `Context` contained concrete tx data.
> 
> So the API might look something like this:
> 
> ```rust
> pub struct Transaction<S: Spec> { 
>    context: Context<S>,
>    msg: Vec<u8>
> }
> 
> impl<S: Spec> Transaction<S>{ 
>   pub fn from_raw_tx(data: &mut &[u8]) -> Result<Self, anyhow::Error> { 
>     let signature = S::Signature::decode(data)?;
>     let (sender, msg) = signature.verify()?;
>     // ... 
>     let context = Context { 
>        sender,
>        // ...
>     };
>     Ok(Self { 
>       context,
>       msg
>     })
>   }
> }
> ```
