### ISSUE TITLE
sov-modules: `Dispatch..` macro should be agnostic to serialization format

### ISSUE THREAD

**Issue by bkolad** [Sovereign-Labs/sovereign#97]
The `DispatchCall/Query` macro derives an enum type based on the underlying structure. Later, the macro derives borsh serialization/deserialization for this enum:
```
// TODO we should not hardcode the serialization format inside the macro.
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize)]
enum #enum_ident #impl_generics #where_clause {
      #(#enum_legs)*
}
```
We should extend the macro and enable users to pass their chosen serialization format (we can use the proc macro attributes mechanism).

**Comment by LukaszRozmej** [comment]
Should the serialization `derive` for the generated enum be mandatory or optional?

**Comment by bkolad** [comment]
> Should the serialization `derive` for the generated enum be mandatory or optional?
It should be mandatory.
